Repository Parsl/parsl, pull requests merged in 2020-07, with the labels that each got.

#1792 Factor out monitoring task info update
  parsl/dataflow/dflow.py
Labels: monitoring, tidying

#1794 Remove outdated/wrong pseudocode in dfk.submit docstring
  parsl/dataflow/dflow.py
Labels: documentation, tidying

#1816 Remove bad paragraph break in checkpoint doc
  docs/userguide/checkpoints.rst
Labels: documentation, memo/checkpoint

#1820 Updating link to point to the updated CODE_OF_CONDUCT.md
  CONTRIBUTING.rst
Labels: documentation

#1819 Correct globus configuration doc subheading level
  docs/userguide/data.rst
Labels: documentation

#1818 Link from dev guide to CONTRIBUTING.md
  docs/devguide/contributing.rst
Labels: documentation

#1817 Rearrange API reference documentation
  docs/README.rst
  docs/devguide/dev_docs.rst
  docs/devguide/index.rst
  docs/reference.rst
  parsl/channels/base.py
  parsl/executors/base.py
  parsl/launchers/launchers.py
  parsl/providers/provider_base.py
Labels: documentation
