Repository Parsl/parsl, pull requests merged in 2024-02, with the labels that each got.

#3030 Protect HTEX communication with CurveZMQ
  docs/userguide/execution.rst
  parsl/curvezmq.py
  parsl/executors/high_throughput/executor.py
  parsl/executors/high_throughput/interchange.py
  parsl/executors/high_throughput/process_worker_pool.py
  parsl/executors/high_throughput/zmq_pipes.py
  parsl/tests/configs/ad_hoc_cluster_htex.py
  parsl/tests/configs/azure_single_node.py
  parsl/tests/configs/bluewaters.py
  parsl/tests/configs/bridges.py
  parsl/tests/configs/cc_in2p3.py
  parsl/tests/configs/comet.py
  parsl/tests/configs/cooley_htex.py
  parsl/tests/configs/ec2_single_node.py
  parsl/tests/configs/ec2_spot.py
  parsl/tests/configs/frontera.py
  parsl/tests/configs/htex_ad_hoc_cluster.py
  parsl/tests/configs/htex_local.py
  parsl/tests/configs/htex_local_alternate.py
  parsl/tests/configs/htex_local_intask_staging.py
  parsl/tests/configs/htex_local_rsync_staging.py
  parsl/tests/configs/local_adhoc.py
  parsl/tests/configs/midway.py
  parsl/tests/configs/nscc_singapore.py
  parsl/tests/configs/osg_htex.py
  parsl/tests/configs/petrelkube.py
  parsl/tests/configs/summit.py
  parsl/tests/configs/swan_htex.py
  parsl/tests/configs/theta.py
  parsl/tests/manual_tests/htex_local.py
  parsl/tests/manual_tests/test_ad_hoc_htex.py
  parsl/tests/manual_tests/test_fan_in_out_htex_remote.py
  parsl/tests/manual_tests/test_memory_limits.py
  parsl/tests/scaling_tests/htex_local.py
  parsl/tests/sites/test_affinity.py
  parsl/tests/sites/test_concurrent.py
  parsl/tests/sites/test_dynamic_executor.py
  parsl/tests/sites/test_worker_info.py
  parsl/tests/test_curvezmq.py
  parsl/tests/test_htex/test_htex.py
  parsl/tests/test_htex/test_htex_zmq_binding.py
  parsl/tests/test_regression/test_97_parallelism_0.py
  parsl/tests/test_scaling/test_block_error_handler.py
  parsl/tests/test_scaling/test_regression_1621.py
  parsl/tests/test_scaling/test_scale_down.py
Labels: htex/exex, globus-compute

#3050 Simplify curvezmq ctx destructor
  parsl/curvezmq.py
Labels: htex/exex, quick-review

#3072 Simplify the Timer class
  parsl/utils.py
Labels: quick-review

#3081 Verify Interchange terminates on HTEX shutdown
  parsl/executors/high_throughput/executor.py
  parsl/multiprocessing.py
  parsl/tests/test_htex/test_htex.py
Labels: bug, htex/exex, globus-compute

#3092 No sense in formatting the already-formatted
  parsl/jobs/states.py
Labels: quick-review

#3093 Replace Comet with Expanse@SDSC in configuration section
  docs/userguide/configuring.rst
  parsl/configs/expanse.py
Labels: documentation, quick-review

#3095 Updating docs to remove retired machines
  docs/userguide/configuring.rst
  parsl/configs/comet.py
  parsl/configs/cooley.py
  parsl/configs/theta.py
Labels: quick-review
